-- 첫 번째 솔루션
SELECT ID, FISH_NAME, LENGTH
FROM (SELECT FISH_TYPE, MAX(LENGTH) l
      FROM FISH_INFO
      GROUP BY FISH_TYPE) m
    LEFT JOIN FISH_NAME_INFO n
    ON m.FISH_TYPE = n.FISH_TYPE
    RIGHT JOIN FISH_INFO i
    ON i.FISH_TYPE = n.FISH_TYPE 
      AND i.LENGTH = m.l
WHERE FISH_NAME IS NOT NULL
ORDER BY ID;


-- 두 번째 솔루션
WITH biggest AS (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT ID, FISH_NAME, LENGTH
FROM FISH_NAME_INFO n RIGHT JOIN 
    (SELECT *
     FROM FISH_INFO 
     WHERE (FISH_TYPE, LENGTH) IN (SELECT * FROM biggest)) i 
    ON i.FISH_TYPE = n.FISH_TYPE
ORDER BY ID